---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- path: content
  label: Pages
  create: all
- path: content/posts
  label: Posts
  create: all
- path: content/projects
  label: Projects
  create: all
- path: content/people
  label: People
  create: all
upload_dir: ''
public_path: https://res.cloudinary.com/forestrydemo1
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
version: 0.42.1
