---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - post
- type: directory
  path: content/projects
  label: Projects
  create: all
  match: "**/*"
  templates:
  - project
- type: directory
  path: content/people
  label: People
  create: all
  match: "**/*"
  templates:
  - person
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
version: 0.42.1
