---
label: default
hide_body: false
is_partial: false
fields:
- type: tag_list
  name: tags
  label: Tags
- type: file
  name: banner_image
  label: Banner Image
  config:
    maxSize: '6'
- type: text
  name: heading
  label: heading
- type: text
  name: sub_heading
  label: sub heading
- type: text
  name: layout
  label: layout
pages:
- content/posts/hugo-at-last.md
- content/about.md
